version: '3'
services:
    cache:
      image: redis
      container_name: 'redis'
      restart: always
      ports:
        - 6379:6379
      command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq-server'
      ports:
          - 5672:5672
          - 15672:15672